name: Create and publish a packages
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  npm-test:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{secrets.npm_token}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        if: env.NODE_AUTH_TOKEN != ''
        with:
          lfs: true
          submodules: true
      - name: Setup Node
        uses: actions/setup-node@v3
        if: env.NODE_AUTH_TOKEN != ''
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - name: Get npm cache directory
        id: npm-cache-dir
        if: env.NODE_AUTH_TOKEN != ''
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - name: Restore cache
        uses: actions/cache@v3
        if: env.NODE_AUTH_TOKEN != ''
        # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install dependencies
        if: env.NODE_AUTH_TOKEN != ''
        run: npm ci --ignore-scripts --no-audit --no-fund
      - name: Publish to npm
        if: env.NODE_AUTH_TOKEN != ''
        run: npm publish --access=public
